theme: jekyll-theme-chirpy

lang: ja
timezone: Asia/Tokyo
future: true
title: "Game Research Archive"
tagline: "個人のゲームアーカイブ"
description: "個人のゲームアーカイブ"
baseurl: "/pj_game_archive"
url: "https://york14.github.io"

social:
  name: York14
  email: ""
  links:
    - https://twitter.com/m_syj
    - https://www.youtube.com/channel/UCtV3aiRUd_MbcuVLz3QEcUA

avatar: /assets/img/home.jpg
image: https://york14.github.io/pj_game_archive/assets/img/posts.jpg

plugins:
  - jekyll-sitemap

math: true

paginate: 10
paginate_path: "/page:num/"
permalink: /posts/:title/