remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
title: "Game Research Archive"
description: "個人のゲーム検証・考察アーカイブ"
baseurl: "/pj_game_archive"
url: "https://york14.github.io"